version: "3"

services:
  postgres:
    image: postgres
    container_name: libre-passport-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=libre-passport
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
